import org.junit.*;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxProfile;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.support.ui.*;
import org.openqa.selenium.remote.RemoteWebDriver;
import java.net.URL;
import java.net.MalformedURLException;
import java.util.Iterator;
import java.util.Set;

import static org.junit.Assert.*;

public class redditTest {

    private WebDriver driver;
    private WebDriverWait wait;


    @Before
    public void setup() throws MalformedURLException {
        FirefoxOptions options = new FirefoxOptions();

        //Disable pop-ups
        options.addArguments("--disable-notifications");
        options.addArguments("--disable-popup-blocking");
        options.addPreference("dom.disable_beforeunload", true);
        FirefoxProfile profile = new FirefoxProfile();

        //allow cookies for the email address, tried to disable them by default by then the email address
        //is not generated
        profile.setPreference("network.cookie.cookieBehavior",0);
        options.setProfile(profile);
        driver = new RemoteWebDriver(new URL("http://selenium:4444/wd/hub"), options);
        driver.manage().window().maximize();

        wait = new WebDriverWait(driver, 30);
    }

    private final By bodyLocator = By.tagName("body");
    private final By searchBarLocator = By.id("header-search-bar");
    private final By searchformLocator = By.xpath("//*[@id=\"SearchDropdown\"]/div/form");

    private final By communitiesButtonLocator = By.xpath("//button[normalize-space()='Communities']");

    private final By cpSubredditLocator = By.xpath("//a[@class='_3BWq3z8_9gA3oThgYXnngR YLZe4_XS9hOtObp1VjEF- _2kqt-kRLvKQ1Kqi8OjMEa7']");

    private final By randomUsernameLocator = By.xpath("/html[1]/body[1]/div[1]/main[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/a[1]");

    private WebElement waitVisibiiltyAndFindElement(By locator) {
        this.wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        return this.driver.findElement(locator);
    }

    @Test
    public void registrationTest() throws InterruptedException {

        //init and get temporary mail
        driver.get("https://mail.tm/en/");
        Thread.sleep(5000);

        //click on the "disagree" button
        driver.findElement(By.xpath("//span[normalize-space()='DISAGREE']")).click();
        WebDriverWait waitForTempMail = new WebDriverWait(driver,120);
        waitForTempMail.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@id='DontUseWEBuseAPI']")));
        //get the email and store it
        String getMail = driver.findElement(By.id("DontUseWEBuseAPI")).getAttribute("value");
        Thread.sleep(5000);

        //System.out.println(getMail); //use this for debug purposes

        //go to reddit register page
        this.driver.get("https://www.reddit.com/register/");

        //wait for the page to load
        WebElement resultElement = waitVisibiiltyAndFindElement(bodyLocator);

        //put mail into login
        WebElement login = driver.findElement(By.id("regEmail"));
        login.sendKeys(getMail);
        //click on the button to proceed
        WebElement loginButton = driver.findElement(By.xpath("//button[@class='AnimatedForm__submitButton m-full-width']"));
        loginButton.click();

        //Get the first random username generated by reddit
        WebElement randomUsername = waitVisibiiltyAndFindElement(randomUsernameLocator);
        System.out.println(randomUsername.getText());

        //Parse it into the username field
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("regUsername")));
        WebElement usernameField = driver.findElement(By.id("regUsername"));
        usernameField.sendKeys(randomUsername.getText());

        //setup a password and put it into the field
        WebElement passField = driver.findElement(By.id("regPassword"));
        passField.sendKeys("passtest");

        //finalize the registration by clicking the button
        loginButton = driver.findElement(By.xpath("//button[normalize-space()='Sign Up']"));
        loginButton.click();

        //30 seconds to complete the captcha
        Thread.sleep(30000);

        loginButton.click();

        //10 seconds for the reddit home page to load up
        Thread.sleep(10000);

        //Getting back to the email address
        driver.get("https://mail.tm/en/");

        //Wait for the page to load and
        //click on the first mail
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//div[@class='flex items-center px-4 py-4 sm:px-6']")));
        driver.findElement(By.xpath("//div[@class='flex items-center px-4 py-4 sm:px-6']")).click();

        //wait until the email is displayed and go into the iframe of it
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.tagName("iframe")));
        WebElement iframe = driver.findElement(By.tagName("iframe"));
        driver.switchTo().frame(iframe);
        //click the vlidation button

        //find and click the confirm registration link
        driver.findElement(By.cssSelector(".link.c-white")).click();
        //exit iframe
        driver.switchTo().defaultContent();

        //stop thread for 15 seconds so the reddit page can load
        Thread.sleep(15000);

        //switch from the mail window to the new reddit window
        Set<String> windowHandles = driver.getWindowHandles();
        Iterator<String> iterator = windowHandles.iterator();
        String parentWindow = iterator.next();
        String childWindow = iterator.next();
        driver.switchTo().window(childWindow);

        //assert the driver is now on the reddit page
        assertTrue(driver.getTitle().equals("r/popular"));

        //find the searchbar of reddit
        WebElement searchBar = waitVisibiiltyAndFindElement(searchBarLocator);
        //input a subreddit to it (here r/cyberpunk)
        searchBar.sendKeys("r/cyberpunkgame");
        searchBar.click();

        //send the form of the searchbar to research the subreddit
        WebElement searchForm = waitVisibiiltyAndFindElement(searchformLocator);
        assertEquals(true, searchForm.isDisplayed());
        searchForm.submit();

        //go into the community tab to find the subreddit
        WebElement buttonCommunities = waitVisibiiltyAndFindElement(communitiesButtonLocator);
        buttonCommunities.click();

        //click on the cyberpunkgame subreddit to access it
        WebElement cpSubreddit = waitVisibiiltyAndFindElement(cpSubredditLocator);
        cpSubreddit.click();

        //wait for the page to load
        Thread.sleep(5000);
        resultElement = waitVisibiiltyAndFindElement(bodyLocator);

        //Check if page loaded
        assertTrue(resultElement.isDisplayed());
        assertEquals("https://www.reddit.com/r/cyberpunkgame/",driver.getCurrentUrl());
        assertEquals("Cyberpunk 2077", driver.getTitle());

        //open the dropdown of our profile (top right corner)
        WebElement drpDown = driver.findElement(By.xpath("//span[@id='email-collection-tooltip-id']"));
        drpDown.click();

        //click on the "logout" button
        WebElement logout = driver.findElement(By.xpath("//span[contains(text(),'Log Out')]"));
        logout.click();

        //TimeUnit.SECONDS.sleep(7);
        resultElement = waitVisibiiltyAndFindElement(bodyLocator);

        //assert we are logged out by locating the "log in" button located on the top right corner
        WebElement loginButtonHomePage = driver.findElement(By.xpath("//*[@id=\"SHORTCUT_FOCUSABLE_DIV\"]/div[1]/header/div/div[2]/div/div[1]/a"));
        assertTrue(loginButtonHomePage.isDisplayed());

    }

    @After
    public void close() {
        if (driver != null) {
            driver.quit();
        }
    }
}
